<?php

namespace KTemplate\Internal\Compile;

// File generated by gen_exprs/main.go; DO NOT EDIT!

class ExprKind {
    public const BAD = 0;
    
    public const IDENT = 1; // $value is string
    public const DOLLAR_IDENT = 2; // $value is string
    public const CALL = 3; // $value is int
    public const BOOL_LIT = 4; // $value is bool
    public const INT_LIT = 5; // $value is int
    public const FLOAT_LIT = 6; // $value is float
    public const STRING_LIT = 7; // $value is string
    public const NULL_LIT = 8;
    public const FILTER = 9;
    public const INDEX = 10;
    public const ADD = 11;
    public const SUB = 12;
    public const MUL = 13;
    public const QUO = 14;
    public const CONCAT = 15;
    public const AND = 16;
    public const OR = 17;
    public const EQ = 18;
    public const NOT_EQ = 19;
    public const LT = 20;
    public const GT = 21;
    public const LT_EQ = 22;
    public const GT_EQ = 23;
    public const MOD = 24;
    public const MATCHES = 25;
    public const DOT_ACCESS = 26;
    public const NOT = 27;
    public const NEG = 28;

	/**
     * @param int $kind
     * @return int
     */
    public static function numArgs($kind) {
        switch ($kind) {
        case self::IDENT:
            return 0;
        case self::DOLLAR_IDENT:
            return 0;
        case self::CALL:
            return -1;
        case self::BOOL_LIT:
            return 0;
        case self::INT_LIT:
            return 0;
        case self::FLOAT_LIT:
            return 0;
        case self::STRING_LIT:
            return 0;
        case self::NULL_LIT:
            return 0;
        case self::NOT:
            return 1;
        case self::NEG:
            return 1;
        default:
            return 2; // The most common number
        }
    }
}
